# Site Settings
title: 'The Kavirra Trials'
description: 'A book series focusing on the heroine Kavirra - set in the future, with magic, demons, and more!'

# Site Variables
company: 'Navala'

# The 'home' link in the navbar is configured here -
# Set these values to change your Homepage:
home_url: '#top-of-page'
home_icon_title: 'Home'

# FrontMatter Settings
permalink: '/:title/' # clean URL's (xyz.com/title vs xyz.com/title.html)

# Build Settings
collections:
  - books

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor

gems:
  - jekyll-assets
  - octopress-minify-html
  - jekyll-sitemap

# Jekyll-Assets
assets:
  sources:
    - _assets/icons